// Generated by CoffeeScript 1.7.1
(function() {
  if (this.Examiner == null) {
    this.Examiner = {};
  }

  Examiner.generateTrials = function(trialList, numReps, method) {
    var allIndices, i, trialListIndices;
    if (numReps == null) {
      numReps = 1;
    } else {
      numReps = Math.max(1, numReps);
    }
    if (method == null) {
      method = 'random';
    }
    if (method === 'random') {
      trialListIndices = _.range(trialList.length);
      allIndices = _.flatten((function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= numReps ? _i < numReps : _i > numReps; i = 0 <= numReps ? ++_i : --_i) {
          _results.push(_.shuffle(trialListIndices));
        }
        return _results;
      })());
      return _.map(allIndices, function(index) {
        return trialList[index];
      });
    } else if (method === 'sequential') {
      return _.flatten((function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= numReps ? _i < numReps : _i > numReps; i = 0 <= numReps ? ++_i : --_i) {
          _results.push(trialList);
        }
        return _results;
      })());
    }
  };

}).call(this);
