#!/bin/sh

# Copyright (c) 2013, Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   1. Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#   2. Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Forcibly update a CouchDB doc

# Usage: ./force-put filename URL [ mime-type ]
FILENAME=$1
URL=$2
MIME_TYPE=$3
if [ -z "$MIME_TYPE" ]; then MIME_TYPE=application-json; fi

# figure out CouchDB doc revision.
LAST_FIELD=5
if [ '_design' = $(echo $URL | cut -d / -f 5) ]; then
    LAST_FIELD=6
fi
REV_URL=$(echo $URL | cut -d / -f 1-$LAST_FIELD)  # get parent doc's URL

REV=$(curl -k -X HEAD $REV_URL -I -s | grep ETag | cut -d '"' -f 2)

if [ -n "$REV" ]; then REV_QUERY="?rev=$REV"; fi

curl -k -X PUT "$URL$REV_QUERY" \
    -f -ss -H "Content-Type: $MIME_TYPE" --data-binary "@$FILENAME" > /dev/null
