#!/usr/bin/env node
// -*- mode: javascript -*-

/*
Copyright (c) 2013, Regents of the University of California
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// print paths from a json file, each followed by a newline.
//
// This supports computing makefile dependencies
// and making cache manifests.
//
// usage: node json-ls.js <levels> [ <file1> [ <file2> ... ] ]
//
// levels tells us what field(s) to look in for filenames.
//
// Examples:
//
// attachments+modules: print contents of attachments and modules field
// /attachments: print paths in attachments field, relative to input file
// tabcat.icon: look in <input data>.tabcat.icon
fs = require('fs');
path = require('path');


if (process.argv.length > 2) {
    var levels = process.argv[2].split('+');
} else {
    var level = [];
}

if (process.argv.length > 3) {
    inputPaths = process.argv.slice(3);
} else {
    inputPaths = [''];
}

var printAtLevel = function(data, level, dirName) {
    // handle level as string from the command line
    if (typeof level == 'string') {
        if (!level) {
            level = [];
            dirName = null;
        } else {
            if (level[0] == '/') {
                level = level.substring('1');
            } else {
                dirName = null;
            }
            level = level.split('.');
        }
    }

    if (Array.isArray(data)) {
        data.forEach(function (item) {
            printAtLevel(item, level, dirName);
        });
    } else if (level.length > 0) {
        if (data != null) {
            printAtLevel(data[level[0]], level.slice(1), dirName);
        }
    } else if (typeof data == 'string') {
        if (dirName) {
            data = path.join(dirName, data);
        }
        process.stdout.write(data);
        process.stdout.write('\n');
    }
};

inputPaths.forEach(function(inputPath) {
    var json = fs.readFileSync(inputPath || '/dev/stdin', 'utf8')
    // ignore empty files
    if (json) {
        var data = JSON.parse(json)
        levels.forEach(function(level) {
            printAtLevel(data, level, path.dirname(inputPath));
        });
    }
});
