#!/bin/sh

# Copyright (c) 2013, Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   1. Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#   2. Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# take paths of kanso files on input (with core/kanso.json first),
# print out a manifest file
set -e

JSON_LS=$(dirname $0)/json-ls

echo CACHE MANIFEST
# use datetime as a nonce, so browser will check if files were updated
echo "# TabCat v$($JSON_LS version $1) $(date)"
echo
echo "CACHE:"
# need this to find the design docs
echo "/tabcat/_all_docs"
for KANSO in "$@"; do
    NAME=$($JSON_LS name $KANSO)
    echo "/tabcat/_design/$NAME"
    # include version with trailing slash, for convenience
    echo "/tabcat/_design/$NAME/"
    # don't include videos because mobile browers can't play them from the
    # application cache anyway
    for FILENAME in $($JSON_LS attachments $KANSO | grep -v -E '\.(mp4|ogv)'); do
        echo "/tabcat/_design/$NAME/$FILENAME"
    done
done

echo
echo "NETWORK:"
echo "*"
