#!/bin/sh
#
# take paths of kanso files on input (with core/kanso.json first),
# print out a manifest file
set -e

JSON_LS=$(dirname $0)/json-ls

echo CACHE MANIFEST
# use datetime as a nonce, so browser will check if files were updated
echo "# TabCat v$($JSON_LS version $1) $(date)"
echo
echo "CACHE:"
# need this to find the design docs
echo "/tabcat/_all_docs"
for KANSO in "$@"; do
    NAME=$($JSON_LS name $KANSO)
    echo "/tabcat/_design/$NAME"
    # include version with trailing slash, for convenience
    echo "/tabcat/_design/$NAME/"
    # don't include videos because mobile browers can't play them from the
    # application cache anyway
    for FILENAME in $($JSON_LS attachments $KANSO | grep -v -E '\.(mp4|ogv)'); do
	echo "/tabcat/_design/$NAME/$FILENAME"
    done
done

echo
echo "NETWORK:"
echo "*"
